# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160924_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.CharField(max_length=200),
        ),
    ]
