# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160925_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
    ]
