# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lambda', '0004_auto_20160925_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lambda.Profile'),
        ),
    ]
